# Generated by Django 2.2.2 on 2019-06-29 14:55

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='A photo of this item', null=True, upload_to='inventory/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.IntegerField(blank=True, help_text='How much did this cost us (in CHF)?', null=True),
        ),
    ]
