# Generated by Django 2.2.22 on 2021-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190706_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('manufacturing', '3D Printing, Scanning, Cutting, Plotting'), ('computers_network', 'Computers & Networking'), ('electronics_lab', 'Electronics Lab'), ('makerspace', 'Makerspace'), ('home_appliances', 'Home Appliances'), ('vintage', 'Vintage Computers')], help_text='In what category does this device belong?', max_length=255, null=True),
        ),
    ]
