# Generated by Django 4.2.18 on 2025-01-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberdb", "0004_remove_member_twitter"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="key_number",
            field=models.CharField(
                blank=True, help_text="Schlüsselnummer", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="key_safe",
            field=models.CharField(
                blank=True,
                choices=[("app", "App"), ("code", "Code")],
                help_text="Art des Schlüsselsafe-Zugriffs",
                max_length=100,
            ),
        ),
    ]
