on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    name: Test
    env:
      DJANGO_DEBUG: 'True'
      PORT: '8000'
      SITE_DOMAIN: 'http://localhost:8000'
      #DATABASE_URL: 'postgres://pg:passw0rd@localhost/interna'
      DATABASE_URL: 'postgres://localhost/interna'
    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          #POSTGRES_USER: pg
          POSTGRES_PASSWORD: passw0rd
          POSTGRES_DB: interna
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create database
        run: createdb -h localhost interna
        #env:
        #  PGPASSWORD: 'passw0rd'
      - name: Run migrations
        run: ./manage.py migrate
      - name: Collect static files
        run: ./manage.py collectstatic --noinput
      - name: Run pytest
        run: pytest
