# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 22:02
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0002_auto_20170820_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=sorl.thumbnail.fields.ImageField(help_text='A photo showing your project', upload_to='crowdfund_projects/'),
        ),
    ]
