# Generated by Django 1.11.4 on 2017-08-27 21:19
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0004_project_initiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingPromise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=100)),
                ('amount', models.PositiveIntegerField(help_text='How much are you willing to pay?')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was this funding offer added?')),
                ('expiry_date', models.DateField(blank=True, help_text='Should this funding offer expire after this date?', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.Project')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
