# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0005_fundingpromise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingpromise',
            name='amount',
            field=models.PositiveIntegerField(help_text='Wie viel würdest du für dieses Projekt bezahlen?'),
        ),
        migrations.AlterField(
            model_name='fundingpromise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Wann wurde dieses Angebot hinzugefügt?'),
        ),
        migrations.AlterField(
            model_name='fundingpromise',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Soll das Angebot irgendwann ablaufen? Lasse dieses Feld leer, wenn das Angebot nie enden soll.', null=True),
        ),
        migrations.AlterField(
            model_name='fundingpromise',
            name='name',
            field=models.CharField(help_text='Dein Name', max_length=100),
        ),
    ]
