# Generated by Django 1.11.4 on 2017-08-27 23:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0006_auto_20170828_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingpromise',
            name='amount',
            field=models.PositiveIntegerField(help_text='Wie viel würdest du für dieses Projekt bezahlen?', verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='fundingpromise',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Soll das Angebot irgendwann ablaufen? Lasse dieses Feld leer, wenn das Angebot nie enden soll.', null=True, verbose_name='Ablaufdatum'),
        ),
        migrations.AlterField(
            model_name='fundingpromise',
            name='name',
            field=models.CharField(help_text='Dein Name', max_length=100, verbose_name='Name'),
        ),
    ]
