# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0007_auto_20170828_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_required',
            field=models.PositiveIntegerField(help_text='Wie viele CHF werden benötigt, um das Projekt zu finanzieren?', verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=sorl.thumbnail.fields.ImageField(help_text='Ein Bild, welches das Projekt repräsentiert', upload_to='crowdfund_projects/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(help_text='Beschreibe dein Projekt im Detail', verbose_name='Detailbeschreibung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Beschreibe dein Projekt mit weniger als 300 Buchstaben', max_length=300, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Titel deines Projektes', max_length=80, verbose_name='Titel'),
        ),
    ]
