# Generated by Django 1.11.4 on 2017-09-10 20:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0008_auto_20170906_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funded',
            field=models.DateTimeField(blank=True, editable=False, help_text='When was this project funded?', null=True),
        ),
    ]
