# Generated by Django 1.11.4 on 2017-09-10 21:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0009_project_funded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funded',
            field=models.DateTimeField(blank=True, help_text='When was this project funded?', null=True),
        ),
    ]
