# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0010_auto_20170910_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forum_thread',
            field=models.URLField(default='https://none/', help_text='Bitte erstelle auf forum.coredump.ch in der Kategorie "Hackerspace" einen Diskussionsthread zu diesem Crowdfunding.', verbose_name='Forums-Thread'),
            preserve_default=False,
        ),
    ]
