# Generated by Django 2.2.19 on 2021-03-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0011_project_forum_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingpromise',
            name='email',
            field=models.EmailField(default='nobody@example.com', help_text='Deine E-Mail-Adresse', max_length=120, verbose_name='E-Mail'),
            preserve_default=False,
        ),
    ]
